In [ ]:
import pandas as pd

In [ ]:
# Open the neighbourhood-profiles-2021-158-model data
import io
from google.colab import files
uploaded = files.upload()

Saving neighbourhood-profiles-2021-158-model(1).xlsx to neighbourhood-profiles-2021-158-model(1).xlsx

(2603, 159)

In [6]:
df = pd.read_excel('/content/neighbourhood-profiles-2021-158-model(1).xlsx')
df.shape

(2603, 159)

In [7]:
#Copy the transpose logic
# We want to tranpose the table such that the first column values become the header
df_neighbourhood_profiles = df.transpose()

# Set the first row as the new header
new_header = df_neighbourhood_profiles.iloc[0]
df_neighbourhood_profiles = df_neighbourhood_profiles[1:]
df_neighbourhood_profiles.columns = new_header

# Display the first few rows with the correct headers
display(df_neighbourhood_profiles.head())

Neighbourhood Name,Neighbourhood Number,TSNS 2020 Designation,Total - Age groups of the population - 25% sample data,0 to 14 years,0 to 4 years,5 to 9 years,10 to 14 years,15 to 64 years,15 to 19 years,20 to 24 years,...,Between 9 a.m. and 11:59 a.m.,Between 12 p.m. and 4:59 a.m.,Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 25% sample data,Children eligible for instruction in the minority official language,Children not eligible for instruction in the minority official language,"Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 25% sample data",Children eligible for instruction in the minority official language,Eligible children who have been instructed in the minority official language at the primary or secondary level in Canada,Eligible children who have not been instructed in the minority official language at the primary or secondary level in Canada,Children not eligible for instruction in the minority official language
West Humber-Clairville,1,Not an NIA or Emerging Neighbourhood,33300,4295,1460,1345,1485,23640,1860,3175,...,1665,2935,5430,410,5020,3875,335,255,75,3540
Mount Olive-Silverstone-Jamestown,2,Neighbourhood Improvement Area,31345,5690,1650,1860,2175,21490,2280,2675,...,1145,2965,7285,510,6780,5540,395,245,145,5145
Thistletown-Beaumond Heights,3,Neighbourhood Improvement Area,9850,1495,505,540,455,6615,570,745,...,395,635,1860,180,1685,1325,120,75,45,1205
Rexdale-Kipling,4,Not an NIA or Emerging Neighbourhood,10375,1575,505,615,455,6950,515,715,...,425,775,1910,135,1770,1370,90,75,25,1275
Elms-Old Rexdale,5,Neighbourhood Improvement Area,9355,1610,440,480,685,6355,635,685,...,355,675,2015,95,1920,1520,70,60,10,1445

In [8]:
#Rename columns with duplicate names
cols=pd.Series(df_neighbourhood_profiles.columns)
for dup in df_neighbourhood_profiles.columns[df_neighbourhood_profiles.columns.duplicated(keep=False)]:
    cols[df_neighbourhood_profiles.columns.get_loc(dup)] = ([dup + '.' + str(d_idx)
                                     if d_idx != 0
                                     else dup
                                     for d_idx in range(df_neighbourhood_profiles.columns.get_loc(dup).sum())]
                                    )
df_neighbourhood_profiles.columns=cols

In [9]:
df_neighbourhood_profiles.columns

Index(['Neighbourhood Number', 'TSNS 2020 Designation',
       'Total - Age groups of the population - 25% sample data',
       '  0 to 14 years', '    0 to 4 years', '    5 to 9 years',
       '    10 to 14 years', '  15 to 64 years', '    15 to 19 years',
       '    20 to 24 years',
       ...
       '  Between 9 a.m. and 11:59 a.m.', '  Between 12 p.m. and 4:59 a.m.',
       'Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 25% sample data',
       '  Children eligible for instruction in the minority official language',
       '  Children not eligible for instruction in the minority official language',
       'Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 25% sample data',
       '  Children eligible for instruction in the minority official language.1',
       '    Eligible children who have been instructed in the minority official language at the primary or secondary level in Canada',
       '    Eligible children who have not been instructed in the minority official language at the primary or secondary level in Canada',
       '  Children not eligible for instruction in the minority official language.1'],
      dtype='object', name='Neighbourhood Name', length=2603)

In [17]:
dfnp_selection = df_neighbourhood_profiles[['Total - Age groups of the population - 25% sample data']]
dfnp_selection = dfnp_selection.rename(columns={'Total - Age groups of the population - 25% sample data': 'POP_TOTAL'})
dfnp_selection['Neighbourhood_Number'] = df_neighbourhood_profiles[['Neighbourhood Number']]
dfnp_selection['POP_AGE_GROUP_0_14'] = df_neighbourhood_profiles[['  0 to 14 years.1']]
dfnp_selection['POP_AGE_GROUP_15_64'] = df_neighbourhood_profiles[['  15 to 64 years.1']]
dfnp_selection['POP_AGE_GROUP_65_'] = df_neighbourhood_profiles[['  65 years and over.1']]
dfnp_selection['POP_AVG_AGE'] = df_neighbourhood_profiles[['Average age of the population']]
dfnp_selection['POP_MED_AGE'] = df_neighbourhood_profiles[['Median age of the population']]
dfnp_selection['MARRIED_%'] = df_neighbourhood_profiles['  Married or living common-law'] / df_neighbourhood_profiles['Total - Marital status for the total population aged 15 years and over - 25% sample data']
dfnp_selection['POP_GOV_SUPP_SHARE'] = df_neighbourhood_profiles[['  Government transfers (%)']]
dfnp_selection['AVG_HHOLD_SIZE'] = df_neighbourhood_profiles[['Average household size']]
dfnp_selection['AVG_TOT_HHOLD_INC'] = df_neighbourhood_profiles[['  Average total income of household in 2020 ($)']]
dfnp_selection['OWNER_HHOLDS_%'] = df_neighbourhood_profiles['  Owner'] / df_neighbourhood_profiles['Total - Private households by tenure - 25% sample data']
dfnp_selection['DW_W_CONDO_STATUS_%'] = df_neighbourhood_profiles['  Condominium'] / df_neighbourhood_profiles['Total - Occupied private dwellings by condominium status - 25% sample data']
dfnp_selection['HHOLDS_UNSUIT_HOU_%'] = df_neighbourhood_profiles['  Not suitable'] / df_neighbourhood_profiles['Total - Private households by housing suitability - 25% sample data']
dfnp_selection['DW_REQ_MAJ_REPAIR_%'] = df_neighbourhood_profiles['  Major repairs needed'] / df_neighbourhood_profiles['Total - Occupied private dwellings by dwelling condition - 25% sample data']
dfnp_selection['SCTI_RAT_GT30_%'] = df_neighbourhood_profiles['  Spending 30% or more of income on shelter costs'] / df_neighbourhood_profiles['Total - Owner and tenant households with household total income greater than zero, in non-farm, non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data']
dfnp_selection['HHOLD_OWN_MRTG_HOLD_%'] = df_neighbourhood_profiles[['  % of owner households with a mortgage']]
dfnp_selection['HHOLD_OWN_SCTI_GT30_%'] = df_neighbourhood_profiles[['  % of owner households spending 30% or more of its income on shelter costs']]
dfnp_selection['AVG_DW_VAL'] = df_neighbourhood_profiles[['  Average value of dwellings ($)']]
dfnp_selection['HHOLDS_IN_SUBS_HOUS_%'] = df_neighbourhood_profiles[['  % of tenant households in subsidized housing']] / 100
dfnp_selection['HHOLDS_OWN_AVG_MNTH_COST'] = df_neighbourhood_profiles[['  Average monthly shelter costs for owned dwellings ($)']]
dfnp_selection['HHOLDS_RENT_AVG_MNTH_COST'] = df_neighbourhood_profiles[['  Average monthly shelter costs for rented dwellings ($)']]
dfnp_selection['AVG_FAM_SIZE'] = df_neighbourhood_profiles[['Average size of census families']]
dfnp_selection['ONE_PAR_FAM_%'] = df_neighbourhood_profiles['  Total one-parent families'] / df_neighbourhood_profiles['Total number of census families in private households - 25% sample data']
dfnp_selection['AVG_NUM_CH_PER_FAM'] = df_neighbourhood_profiles[['Average number of children in census families with children']]
dfnp_selection['HHOLD_FIRST_LANG_EN_%'] = df_neighbourhood_profiles['  English'] / df_neighbourhood_profiles['Total - First official language spoken for the population in private households - 25% sample data']
dfnp_selection['HHOLD_FIRST_LANG_FR_%'] = df_neighbourhood_profiles['  French'] / df_neighbourhood_profiles['Total - First official language spoken for the population in private households - 25% sample data']
dfnp_selection['HHOLD_FIRST_LANG_ENFR_%'] = df_neighbourhood_profiles['  English and French'] / df_neighbourhood_profiles['Total - First official language spoken for the population in private households - 25% sample data']
dfnp_selection['HHOLD_FIRST_LANG_OTH_%'] = df_neighbourhood_profiles['  Neither English nor French'] / df_neighbourhood_profiles['Total - First official language spoken for the population in private households - 25% sample data']
dfnp_selection['POP_NONCITIZ_%'] = df_neighbourhood_profiles['  Not Canadian citizens'] / df_neighbourhood_profiles['Total - Citizenship for the population in private households - 25% sample data']
dfnp_selection['POP_NON_IMMIGR_%'] = df_neighbourhood_profiles['  Non-immigrants'] / df_neighbourhood_profiles['Total - Immigrant status and period of immigration for the population in private households - 25% sample data']
dfnp_selection['POP_IMMIGR_%'] = df_neighbourhood_profiles['  Immigrants'] / df_neighbourhood_profiles['Total - Immigrant status and period of immigration for the population in private households - 25% sample data']
dfnp_selection['POP_TEMP_RES_%'] = df_neighbourhood_profiles['  Non-permanent residents'] / df_neighbourhood_profiles['Total - Immigrant status and period of immigration for the population in private households - 25% sample data']
dfnp_selection['PARTICIP_RATE'] = df_neighbourhood_profiles[['Participation rate']]
dfnp_selection['UNEMPLOY_RATE'] = df_neighbourhood_profiles[['Unemployment rate']]
dfnp_selection['POP_NO_EDUC_%'] = df_neighbourhood_profiles['  No certificate, diploma or degree.1'] / df_neighbourhood_profiles['Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households - 25% sample data']
dfnp_selection['POP_HIGH_SCH_EDUC_%'] = df_neighbourhood_profiles['  High (secondary) school diploma or equivalency certificate.1'] / df_neighbourhood_profiles['Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households - 25% sample data']
dfnp_selection['POP_POSTSEC_EDUC_%'] = df_neighbourhood_profiles['  Postsecondary certificate, diploma or degree.1'] / df_neighbourhood_profiles['Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households - 25% sample data']
dfnp_selection['COMMUTE_CAR_%'] = df_neighbourhood_profiles['  Car, truck or van'] / df_neighbourhood_profiles['Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_TRANSIT_%'] = df_neighbourhood_profiles['  Public transit'] / df_neighbourhood_profiles['Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_WALK_%'] = df_neighbourhood_profiles['  Walked'] / df_neighbourhood_profiles['Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_CYCLE_%'] = df_neighbourhood_profiles['  Bicycle'] / df_neighbourhood_profiles['Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_OTHER_%'] = df_neighbourhood_profiles['  Other method'] / df_neighbourhood_profiles['Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_LT_30_MIN_%'] = (df_neighbourhood_profiles['  Less than 15 minutes'] + df_neighbourhood_profiles['  15 to 29 minutes']) / df_neighbourhood_profiles['Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_30_59_MIN_%'] = (df_neighbourhood_profiles['  30 to 44 minutes'] + df_neighbourhood_profiles['  45 to 59 minutes']) / df_neighbourhood_profiles['Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_GT_59_MIN_%'] = df_neighbourhood_profiles['  60 minutes and over'] / df_neighbourhood_profiles['Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_START_5_6_AM_%'] = df_neighbourhood_profiles['  Between 5 a.m. and 5:59 a.m.'] / df_neighbourhood_profiles['Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_START_6_7_AM_%'] = df_neighbourhood_profiles['  Between 6 a.m. and 6:59 a.m.'] / df_neighbourhood_profiles['Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_START_7_8_AM_%'] = df_neighbourhood_profiles['  Between 7 a.m. and 7:59 a.m.'] / df_neighbourhood_profiles['Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_START_8_9_AM_%'] = df_neighbourhood_profiles['  Between 8 a.m. and 8:59 a.m.'] / df_neighbourhood_profiles['Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_START_9_AM_noon_%'] = df_neighbourhood_profiles['  Between 9 a.m. and 11:59 a.m.'] / df_neighbourhood_profiles['Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection['COMMUTE_START_noon_5_AM_%'] = df_neighbourhood_profiles['  Between 12 p.m. and 4:59 a.m.'] / df_neighbourhood_profiles['Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data']
dfnp_selection.head(5)

Neighbourhood Name,POP_TOTAL,Neighbourhood_Number,POP_AGE_GROUP_0_14,POP_AGE_GROUP_15_64,POP_AGE_GROUP_65_,POP_AVG_AGE,POP_MED_AGE,MARRIED_%,POP_GOV_SUPP_SHARE,AVG_HHOLD_SIZE,...,COMMUTE_OTHER_%,COMMUTE_LT_30_MIN_%,COMMUTE_30_59_MIN_%,COMMUTE_GT_59_MIN_%,COMMUTE_START_5_6_AM_%,COMMUTE_START_6_7_AM_%,COMMUTE_START_7_8_AM_%,COMMUTE_START_8_9_AM_%,COMMUTE_START_9_AM_noon_%,COMMUTE_START_noon_5_AM_%
West Humber-Clairville,33300,1,12.9,71,16.1,40.5,38,0.493793,25.8,3.1,...,0.016641,0.518189,0.350232,0.131192,0.075851,0.189241,0.20356,0.175697,0.12887,0.227167
Mount Olive-Silverstone-Jamestown,31345,2,18.2,68.6,13.3,37.8,36,0.469408,35.2,3.2,...,0.021728,0.486914,0.379753,0.13284,0.077531,0.180741,0.18321,0.152099,0.113086,0.29284
Thistletown-Beaumond Heights,9850,3,15.2,67.2,17.7,41,39.2,0.496709,27.5,3,...,0.032689,0.500743,0.33581,0.163447,0.072808,0.20208,0.221397,0.196137,0.117385,0.188707
Rexdale-Kipling,10375,4,15.2,67,17.8,41.9,42,0.472727,26.6,2.6,...,0.021739,0.512228,0.338315,0.152174,0.092391,0.188859,0.210598,0.180707,0.115489,0.210598
Elms-Old Rexdale,9355,5,17.2,67.9,14.9,39.6,38.4,0.438993,29.4,2.9,...,0.028668,0.527825,0.350759,0.121417,0.084317,0.197302,0.198988,0.172007,0.11973,0.227656

In [18]:
scalingColumns = ['POP_AGE_GROUP_0_14','POP_AGE_GROUP_15_64','POP_AGE_GROUP_65_','POP_AVG_AGE','POP_MED_AGE','MARRIED_%','AVG_HHOLD_SIZE','AVG_TOT_HHOLD_INC',
                  'AVG_DW_VAL','HHOLDS_OWN_AVG_MNTH_COST','HHOLDS_RENT_AVG_MNTH_COST','AVG_FAM_SIZE','AVG_NUM_CH_PER_FAM'];

In [19]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define different scalers
minmax_scaler = MinMaxScaler()
standard_scaler = StandardScaler()
robust_scaler = RobustScaler()

# Create a ColumnTransformer to apply different scalers to different columns
# You can customize this based on which scaling method you want for each column
# For example, you could have specific columns scaled with StandardScaler, others with MinMaxScaler, etc.
# Here, I'm demonstrating how to apply a different scaler to each column for illustration.
# In a real scenario, you would likely choose one or two scaling methods and apply them to groups of columns.

# Example: Applying different scalers to a few columns
# For simplicity and demonstration, I'll apply a different scaler to the first 3 columns
# and then apply StandardScaler to the rest of the scalingColumns.
# You should adjust this based on your specific requirements.

transformers = [
    #('minmax', minmax_scaler, scalingColumns)
    ('standard', standard_scaler, scalingColumns)
    #('robust', robust_scaler, scalingColumns)
    #('standard_rest', standard_scaler, scalingColumns)
]

preprocessor = ColumnTransformer(transformers=transformers, remainder='passthrough')

# Create a pipeline that first applies the preprocessor and then does nothing further (for demonstration)
# In a real application, you would typically add a model after the preprocessor.
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Fit and transform the selected columns
dfnp_scaled = pipeline.fit_transform(dfnp_selection[scalingColumns])

# To see the result as a DataFrame (optional)
# Get the column names after transformation
# The order of columns in the transformed array will be based on the order in the transformers list
# and then the 'remainder' columns (which we set to 'passthrough', but there are none in this case as we selected specific columns)
# You might need to adjust this if you have 'remainder' columns.
transformed_column_names = [t[0] for t in preprocessor.transformers_ if t[2] is not None]
# Since we are transforming all columns in scalingColumns, the transformed columns will correspond to these names
transformed_dfnp_selection = pd.DataFrame(dfnp_scaled, columns=scalingColumns)

display(transformed_dfnp_selection.head())

,POP_AGE_GROUP_0_14,POP_AGE_GROUP_15_64,POP_AGE_GROUP_65_,POP_AVG_AGE,POP_MED_AGE,MARRIED_%,AVG_HHOLD_SIZE,AVG_TOT_HHOLD_INC,AVG_DW_VAL,HHOLDS_OWN_AVG_MNTH_COST,HHOLDS_RENT_AVG_MNTH_COST,AVG_FAM_SIZE,AVG_NUM_CH_PER_FAM
0,-0.321216,0.291588,-0.139260,-0.312234,-0.623757,-0.318403,1.533931,-0.347566,-0.623559,-0.839122,-0.500952,0.566975,0.753743
1,1.222908,-0.113283,-0.762201,-1.348804,-1.116033,-0.754443,1.773182,-0.653889,-0.918392,-0.873405,-0.729563,1.924277,2.114789
2,0.348876,-0.349457,0.216706,-0.120277,-0.328392,-0.266271,1.294681,-0.401131,-0.362141,-0.790147,-0.898013,1.019409,1.434266
3,0.348876,-0.383197,0.238954,0.225246,0.360795,-0.695084,0.337677,-0.590281,-0.552799,-1.128077,-0.973214,0.566975,0.753743
4,0.931564,-0.231370,-0.406235,-0.657758,-0.525302,-1.298294,1.055430,-0.513282,-0.841735,-0.951766,-0.645338,1.019409,1.434266

In [22]:
import pandas as pd
# Keep the non-scaled columns
dfnp_non_scaled = dfnp_selection[['Neighbourhood_Number']]

# Reset the index of the transformed DataFrame to align with the original
transformed_dfnp_selection.reset_index(drop=True, inplace=True)
dfnp_non_scaled.reset_index(drop=True, inplace=True)

# Concatenate the non-scaled columns with the scaled columns
df_final = pd.concat([dfnp_non_scaled, transformed_dfnp_selection], axis=1)

# Display the first few rows of the final DataFrame
display(df_final.head())

,Neighbourhood_Number,POP_AGE_GROUP_0_14,POP_AGE_GROUP_15_64,POP_AGE_GROUP_65_,POP_AVG_AGE,POP_MED_AGE,MARRIED_%,AVG_HHOLD_SIZE,AVG_TOT_HHOLD_INC,AVG_DW_VAL,HHOLDS_OWN_AVG_MNTH_COST,HHOLDS_RENT_AVG_MNTH_COST,AVG_FAM_SIZE,AVG_NUM_CH_PER_FAM
0,1,-0.321216,0.291588,-0.139260,-0.312234,-0.623757,-0.318403,1.533931,-0.347566,-0.623559,-0.839122,-0.500952,0.566975,0.753743
1,2,1.222908,-0.113283,-0.762201,-1.348804,-1.116033,-0.754443,1.773182,-0.653889,-0.918392,-0.873405,-0.729563,1.924277,2.114789
2,3,0.348876,-0.349457,0.216706,-0.120277,-0.328392,-0.266271,1.294681,-0.401131,-0.362141,-0.790147,-0.898013,1.019409,1.434266
3,4,0.348876,-0.383197,0.238954,0.225246,0.360795,-0.695084,0.337677,-0.590281,-0.552799,-1.128077,-0.973214,0.566975,0.753743
4,5,0.931564,-0.231370,-0.406235,-0.657758,-0.525302,-1.298294,1.055430,-0.513282,-0.841735,-0.951766,-0.645338,1.019409,1.434266

In [20]:
display(dfnp_selection)

Neighbourhood Name,POP_TOTAL,Neighbourhood_Number,POP_AGE_GROUP_0_14,POP_AGE_GROUP_15_64,POP_AGE_GROUP_65_,POP_AVG_AGE,POP_MED_AGE,MARRIED_%,POP_GOV_SUPP_SHARE,AVG_HHOLD_SIZE,...,COMMUTE_OTHER_%,COMMUTE_LT_30_MIN_%,COMMUTE_30_59_MIN_%,COMMUTE_GT_59_MIN_%,COMMUTE_START_5_6_AM_%,COMMUTE_START_6_7_AM_%,COMMUTE_START_7_8_AM_%,COMMUTE_START_8_9_AM_%,COMMUTE_START_9_AM_noon_%,COMMUTE_START_noon_5_AM_%
West Humber-Clairville,33300,1,12.9,71,16.1,40.5,38,0.493793,25.8,3.1,...,0.016641,0.518189,0.350232,0.131192,0.075851,0.189241,0.20356,0.175697,0.12887,0.227167
Mount Olive-Silverstone-Jamestown,31345,2,18.2,68.6,13.3,37.8,36,0.469408,35.2,3.2,...,0.021728,0.486914,0.379753,0.13284,0.077531,0.180741,0.18321,0.152099,0.113086,0.29284
Thistletown-Beaumond Heights,9850,3,15.2,67.2,17.7,41,39.2,0.496709,27.5,3,...,0.032689,0.500743,0.33581,0.163447,0.072808,0.20208,0.221397,0.196137,0.117385,0.188707
Rexdale-Kipling,10375,4,15.2,67,17.8,41.9,42,0.472727,26.6,2.6,...,0.021739,0.512228,0.338315,0.152174,0.092391,0.188859,0.210598,0.180707,0.115489,0.210598
Elms-Old Rexdale,9355,5,17.2,67.9,14.9,39.6,38.4,0.438993,29.4,2.9,...,0.028668,0.527825,0.350759,0.121417,0.084317,0.197302,0.198988,0.172007,0.11973,0.227656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yonge-Bay Corridor,12645,170,7.7,85.6,6.8,34.5,31,0.412243,7.9,1.7,...,0.03858,0.682099,0.25,0.070988,0.018519,0.109568,0.229938,0.324074,0.214506,0.101852
Junction-Wallace Emerson,23180,171,13.3,74.2,12.5,39.6,37.6,0.516667,17,2.3,...,0.038989,0.454874,0.443321,0.103249,0.068592,0.172563,0.19278,0.236101,0.171119,0.159567
Dovercourt Village,12380,172,11,73,16,41.9,39.2,0.497957,16.8,2.3,...,0.030043,0.490701,0.429185,0.081545,0.052933,0.131617,0.197425,0.236052,0.221745,0.16309
North Toronto,15885,173,8.3,80.5,11.3,39.2,35.2,0.458476,13.2,1.7,...,0.031938,0.409692,0.488987,0.102423,0.030837,0.125551,0.23348,0.276432,0.213656,0.121145
South Eglinton-Davisville,22735,174,9.6,77,13.4,40.1,36,0.49063,10.3,1.7,...,0.035508,0.468208,0.440958,0.090834,0.028902,0.099092,0.224608,0.297275,0.229562,0.120562

In [23]:
# prompt: save transformed_dfnp_selection to a csv

df_final.to_csv('df_neighbourhoods.csv', index=False)